### ISSUE TITLE
A list of bugs I found.

### ISSUE THREAD

**Issue by jdev082** [warpdesign/react-explorer#237] opened 2022-06-13 14:13 UTC
- When folder can not be read due to permission issues, it just doesn't work not even providing an error.
- Close tab does not work.
- Select next tab does not work.
- Application can not be closed, from menu or close button. When the close option in the menu is clicked, the app goes black and continues to not close. (linux)
- ~~Open Terminal option does not function properly (linux)~~ <-- works with proper config
- When too many tabs are open, the directory icon downscales until its eventually invisible.

**Comment by JaydenDev** [comment] 2022-06-13 14:13
I only searched the first page of issues, to find duplicates. So if a duplicate is found, tell me and I can remove it from the list.

**Comment by warpdesign** [comment] 2022-06-14 07:41
Thanks a lot for reporting these issues!

I need to do more testing on Linux.

- you're using the AppImage version?
- once you stumble upon a bug could you open the console by pressing `ctrl+alt+i` and send me any error that appear here?

**Comment by JaydenDev** [comment] 2022-06-14 14:49
> 

Yes, I am using the AppImage version. No visible errors in console, as these options aren't bugs. Just information that should be hidden. The issue is, that it's reading the EFI and swap partitions.

**Comment by warpdesign** [comment] 2022-10-06 13:15
I tried the latest dev build + 2.3.1 deb package on Linux (MX Linux) but could not reproduce most of the reported problems:
- closing tab worked as expected
- attempting to open ` /root`  shows a permission error as expected
- application exited as expected
- selecting next tab also works
Could you provide more details please? like the distribution you have and the way the app was installed?

**Comment by warpdesign** [comment] 2023-01-24 10:40
Closing: feel free to reopen if you can provide instructions on how to reproduce the bugs.

**Closed by warpdesign** 2023-01-24 10:40 UTC
Labels: bug, needs more info
